const SECTORS=[
 {id:'household',icon:'⚱',name:'Предметы быта',desc:'Орудия, одежда и повседневная жизнь'},
 {id:'geography',icon:'⌖',name:'География Библии',desc:'Города, земли, реки и горы'},
 {id:'people',icon:'♔',name:'Люди Библии',desc:'Пророки, цари, судьи и ученики'},
 {id:'nature',icon:'❧',name:'Растения и животные',desc:'Всё живое на страницах Писания'},
 {id:'chronology',icon:'⌛',name:'Хронология',desc:'Даты, периоды и последовательность'},
 {id:'erudite',icon:'✦',name:'Эрудит',desc:'Испытание для знатоков Библии'}
];
const VALUES=[200,400,600,800,1000];
const state={teamCount:2,teams:[],current:0,turn:1,card:null,cellValue:200,cellKey:'',used:new Set(),opened:new Set(),letters:new Set(),solved:0,sound:true,wheelValue:10};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function tone(type){if(!state.sound)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const c=tone.ctx||(tone.ctx=new A),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);const now=c.currentTime;let f=type==='good'?660:type==='bad'?140:330;o.frequency.setValueAtTime(f,now);if(type==='good')o.frequency.exponentialRampToValueAtTime(990,now+.25);g.gain.setValueAtTime(.08,now);g.gain.exponentialRampToValueAtTime(.001,now+.38);o.start(now);o.stop(now+.4)}
function renderFields(){const old=[...$$('.team-field input')].map(x=>x.value);$('#team-fields').innerHTML=Array.from({length:state.teamCount},(_,i)=>`<div class="team-field"><label>Команда ${['I','II','III'][i]}</label><input maxlength="24" value="${old[i]||'Команда '+(i+1)}" aria-label="Название команды ${i+1}"></div>`).join('')}
function makeTeams(){state.teams=[...$$('.team-field input')].map((x,i)=>({name:x.value.trim()||`Команда ${i+1}`,score:0,solved:0}));state.current=0;state.turn=1;state.solved=0;state.used.clear();state.opened.clear()}
function draw(){makeTeams();show('lottery');const die=$('#die'),status=$('#draw-status'),go=$('#proceed');go.classList.add('hidden');die.classList.add('spinning');let ticks=0;const timer=setInterval(()=>{status.textContent=state.teams[ticks%state.teams.length].name+'…';if(++ticks>=15){clearInterval(timer);state.current=Math.floor(Math.random()*state.teams.length);die.classList.remove('spinning');status.innerHTML=`Ходит: <strong>${state.teams[state.current].name}</strong>`;go.classList.remove('hidden');tone('good')}},200)}
function renderBoard(){$('#current-team').textContent=state.teams[state.current].name;$('#turn-count').textContent=state.turn;$('#scoreboard').innerHTML=state.teams.map((t,i)=>`<div class="score-chip ${i===state.current?'current':''}">${t.name} <b>${t.score}</b></div>`).join('');$('#sector-grid').innerHTML=`<div class="quiz-table"><div class="quiz-head"><span>Раздел</span>${VALUES.map(v=>`<b>${v}</b>`).join('')}</div>${SECTORS.map(s=>`<div class="quiz-row"><div class="quiz-category"><span>${s.icon}</span><strong>${s.name}</strong><small>${s.desc}</small></div>${VALUES.map(v=>{const key=`${s.id}-${v}`,done=state.opened.has(key);return `<button class="point-cell ${done?'opened':''}" data-sector="${s.id}" data-value="${v}" ${done?'disabled':''}><span>${done?'✓':v}</span></button>`}).join('')}</div>`).join('')}</div>`;$$('.point-cell:not(:disabled)').forEach(b=>b.onclick=()=>startPuzzle(b.dataset.sector,+b.dataset.value));show('board')}
function available(sector,value){const tier=VALUES.indexOf(value);const pool=BIBLE_CARDS.filter(c=>c.category===sector&&!state.used.has(c.id)).sort((a,b)=>normalized(a.answer).length-normalized(b.answer).length);const from=Math.floor(pool.length*tier/VALUES.length),to=Math.max(from+1,Math.floor(pool.length*(tier+1)/VALUES.length));return pool.slice(from,to)}
function startPuzzle(sector,value){const pool=available(sector,value);if(!pool.length){finish();return}state.card=pool[Math.floor(Math.random()*pool.length)];state.cellValue=value;state.cellKey=`${sector}-${value}`;state.opened.add(state.cellKey);state.letters.clear();state.wheelValue=Math.max(10,value/20);$('#puzzle-category').textContent=state.card.categoryName;$('#puzzle-reference').textContent=state.card.reference||'Библейская викторина';$('#puzzle-value').textContent=value+' очков';$('#question').textContent=state.card.question;$('#letter-input').value='';setMessage('');updateWord();show('puzzle');spinWheel();tone('page')}
function normalized(s){return s.toLocaleUpperCase('ru').replace(/Ё/g,'Е').replace(/[^А-ЯA-Z0-9]/g,'')}
function updateWord(){const chars=[...state.card.answer.toLocaleUpperCase('ru')];$('#masked-word').innerHTML=chars.map(ch=>{if(/[^А-ЯЁA-Z0-9]/.test(ch))return `<span class="space">${ch===' '?'&nbsp;':ch}</span>`;const open=state.letters.has(ch.replace('Ё','Е'));return `<span>${open?ch:'·'}</span>`}).join('');$('#used-letters').textContent=state.letters.size?'Названо: '+[...state.letters].join(' · '):'Буквы ещё не называли'}
function spinWheel(){const base=Math.max(10,state.cellValue/20),vals=[base,base,base*1.5,base*2],v=Math.round(vals[Math.floor(Math.random()*vals.length)]);state.wheelValue=v;$('#wheel').style.transform=`rotate(${720+Math.floor(Math.random()*360)}deg)`;$('#wheel-label').textContent='Вращаем барабан…';setTimeout(()=>$('#wheel-label').textContent=`На барабане: ${v}`,1400)}
function setMessage(text,type=''){const m=$('#message');m.textContent=text;m.className='message '+type}
function guessLetter(){const inp=$('#letter-input'),letter=normalized(inp.value);inp.value='';inp.focus();if(letter.length!==1){setMessage('Введите одну букву.','bad');return}if(state.letters.has(letter)){setMessage('Эту букву уже называли.','bad');return}state.letters.add(letter);const answer=normalized(state.card.answer),count=[...answer].filter(x=>x===letter).length;updateWord();if(count){const gain=state.wheelValue*count;state.teams[state.current].score+=gain;setMessage(`Верно! Букв: ${count}. +${gain} очков.`,'good');tone('good');if([...answer].every(x=>state.letters.has(x)))solveCard(gain);else spinWheel()}else{setMessage('Такой буквы нет. Ход переходит дальше.','bad');tone('bad');setTimeout(nextTurn,1200)}}
function solveCard(){state.used.add(state.card.id);state.teams[state.current].solved++;state.solved++;setMessage(`Слово открыто: ${state.card.answer}!`,'good');tone('good');setTimeout(()=>state.solved>=12?finish():nextTurn(),1600)}
function guessWhole(){const value=$('#word-input').value.trim();if(!value)return;if(normalized(value)===normalized(state.card.answer)){const bonus=state.cellValue;state.teams[state.current].score+=bonus;$('#word-dialog').close();setMessage(`Точный ответ! +${bonus} очков.`,'good');solveCard()}else{$('#word-dialog').close();setMessage(`Неверно. Правильный ответ: ${state.card.answer}.`,'bad');state.used.add(state.card.id);tone('bad');setTimeout(nextTurn,1600)}}
function nextTurn(){state.current=(state.current+1)%state.teams.length;state.turn++;renderBoard()}
function finish(){if(!state.teams.length){show('welcome');return}const sorted=[...state.teams].sort((a,b)=>b.score-a.score),top=sorted[0].score,winners=sorted.filter(x=>x.score===top);$('#winner-title').textContent=winners.length>1?'Победила дружба!':'Победитель — '+winners[0].name;$('#final-scores').innerHTML=sorted.map(t=>`<div class="final-row ${t.score===top?'winner':''}"><span>${t.name}</span><span>${t.solved} слов</span><b>${t.score} очков</b></div>`).join('');show('results');tone('good')}
$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$$('.cameo').forEach(b=>b.onclick=()=>{state.teamCount=+b.dataset.count;$$('.cameo').forEach(x=>x.classList.toggle('selected',x===b));renderFields()});$('#draw-btn').onclick=draw;$('#proceed').onclick=renderBoard;$('#back-board').onclick=renderBoard;$('#guess-letter').onclick=guessLetter;$('#letter-input').onkeydown=e=>{if(e.key==='Enter')guessLetter()};$('#guess-word').onclick=()=>{$('#word-input').value='';$('#word-dialog').showModal();setTimeout(()=>$('#word-input').focus(),50)};$('#submit-word').onclick=e=>{e.preventDefault();guessWhole()};$('#word-input').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();guessWhole()}};$('#finish-game').onclick=finish;$('#play-again').onclick=()=>{state.teams.forEach(t=>{t.score=0;t.solved=0});state.turn=1;state.solved=0;state.used.clear();renderBoard()};$('#sound-toggle').onclick=e=>{state.sound=!state.sound;e.currentTarget.textContent=state.sound?'♪':'×'};
$('#play-again').addEventListener('click',()=>state.opened.clear(),{capture:true});
renderFields();
